### ISSUE TITLE
Make text segments (PdfPageTextSegments) support start index.

### ISSUE THREAD

**Issue by zhonghua-wang** [ajrcarey/pdfium-render#110]
HI, current `PdfPageTextSegments` struct can only represents segments start from index `0` to the **end** (the `characters` property), add a `start` property may be applicable to more scenarios, e.g., get the segments of user selected text. Should I submit a pr?

change
```rust
pub struct PdfPageTextSegments<'a> {
    text: &'a PdfPageText<'a>,
    characters: i32,
    bindings: &'a dyn PdfiumLibraryBindings,
}
``` 
to 
```rust
pub struct PdfPageTextSegments<'a> {
    text: &'a PdfPageText<'a>,
    start: i32,
    characters: i32,
    bindings: &'a dyn PdfiumLibraryBindings,
}
```

**Comment by ajrcarey** [comment]
Reworked and simplified `example/text-search.rs`. Reworked PdfSearchOptions to use builder pattern. Added PdfSearchDirection enum in favour of specifying search direction by boolean. Made minor naming changes to various items. Added doc comments for all new functionality. Updated READMEs. Ready to release as part of crate version 0.8.13.
