### ISSUE TITLE
Missing FPDF_DeviceToPage and FPDF_PageToDevice impl for StaticPdfiumBindings

### ISSUE THREAD

**Issue by linxGnu** [ajrcarey/pdfium-render#112]
Hi, could you please check v0.8.12 in which functions in trait PdfiumLibraryBindings are missing

```
31  |   impl PdfiumLibraryBindings for StaticPdfiumBindings {
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `FPDF_DeviceToPage`, `FPDF_PageToDevice` in implementation
```

**Comment by ajrcarey** [comment]
Hi @linxGnu , thank you for reporting the issue. I have pushed a commit that adds the missing bindings for static linking. You can take `pdfium-render` as a git dependency in your Cargo.toml to access the bindings prior to the release of 0.8.13.

Follow-on from #108 .

**Comment by linxGnu** [comment]
Thank you so much. It's great help. 

Please feel free to close this issue :)

**Comment by ajrcarey** [comment]
No problem. I'll leave the issue open until 0.8.13 is released.
