### ISSUE TITLE
Page 1 rendered with error when testing with watermark.rs

### ISSUE THREAD

**Issue by wkwi2r** [ajrcarey/pdfium-render#124]
Using release v0.8.16, the following is screen shot of Page 1 of the output PDF after I ran watermark.rs:

![image](https://github.com/ajrcarey/pdfium-render/assets/139043415/3bf32ad6-0228-46a9-911f-57e92dff08fe)

**Comment by ajrcarey** [comment]
Is this using the watermark.rs example in the repo?

**Comment by ajrcarey** [comment]
Assuming this is using the watermark.rs example in the repo, do you see garbled output on every page, or just the first page? (Aside from the watermark itself, every page should be the same as in the tests/export-test.pdf file.)

**Comment by ajrcarey** [comment]
Switched source file from `test/export-test.pdf` to `test/text-test.pdf` in `examples/watermark.rs`.
