### ISSUE TITLE
Mutate Metadata

### ISSUE THREAD

**Issue by seanaye** [ajrcarey/pdfium-render#127]
I see its possible to read pdf metadata but it doesn't appear to be possible to delete the metadata.

It would be great if the crate allows for the deletion of pdf metadata

https://docs.rs/pdfium-render/latest/pdfium_render/metadata/struct.PdfMetadata.html

**Comment by ajrcarey** [comment]
Hi @seanaye , Pdfium provides a function to read document metadata (`FPDF_GetMetaText`), but no corresponding functions to mutate or delete metadata. There is no intention for `pdfium-render` to offer functionality that Pdfium does not itself provide. You would need to lodge a feature request upstream with the Pdfium project to add the ability to mutate metadata there; once Pdfium supports the functionality upstream, please feel free to open a new issue to have it added to `pdfium-render`.
