### ISSUE TITLE
Attempt to add a subset of the font library to reduce the size of the PDF

### ISSUE THREAD

**Issue by 1000374** [ajrcarey/pdfium-render#133]
such as, 
1. add "你好", then add "abc",
 each time extract the character subset  and then call FPDFText_ LoadFont
2. "你好abc", get character subset and then call FPDFText_ LoadFont
file 2 is much larger than file 1 in size
so I don't know how to use it，any suggestions would be greatly appreciated

**Comment by ajrcarey** [comment]
Hi @1000374 , thank you for reporting the issue. Pdfium doesn't provide any control (that I am aware of) over which glyphs of a font are embedded in the file. Can you provide some sample code for your #1 and #2 that demonstrate the difference in file size?

**Comment by ajrcarey** [comment]
As there have been no further comments and I am not clear on what you are asking, I will shortly close the issue.

**Comment by ajrcarey** [comment]
Closing the issue as insufficient information as been provided in order to proceed.
