### ISSUE TITLE
Can we modify the text of a PDF in-place?

### ISSUE THREAD

**Issue by jymchng** [ajrcarey/pdfium-render#150]
As title and I don't think we can since we are allocating new storage for the text each time we attempt to get them.

**Comment by ajrcarey** [comment]
Hi @jymchng , thank you for the question. You can modify the text of a page text object in-place using the `PdfPageTextObject::set_text()` method: https://docs.rs/pdfium-render/0.8.22/pdfium_render/page_object_text/struct.PdfPageTextObject.html#method.set_text

This will not necessarily avoid allocations - that depends on how you allocate strings in your application. Additionally, even if you use static &str's in your application, it is possible that Pdfium itself may make additional allocations in its own code.

Note that modifying the text of a page text object does not change any of the other properties of that text object. Its font settings, placement on its containing page, and rendering matrix will all remain the same. So whether this approach is workable for you or not depends very much on what you are trying to do.

**Comment by jymchng** [comment]
Hi @ajrcarey 

Thank you for your prompt and comprehensive response.

I am attempting to write an application that redacts text specified by regexes [(link)](https://github.com/jymchng/raf). I believe this crate can help me with the redacting `.pdf`s. I will give it a try soon.

I had trouble with `lopdf` because the encoding and decoding part is not complete.

**Comment by ajrcarey** [comment]
_In theory_, it's straight-forward:

* For each page `p`
* For each page object `o` on page `p`
* If `o` is a page text object...
* ... then retrieve the text inside `o`, search it for the target string, and replace it with the redacted string

You can see an example of iterating over every object in every page of a document at https://github.com/ajrcarey/pdfium-render/blob/master/examples/objects.rs.

_In practice_, you're likely to encounter situations where the application used to create the source PDF has done weird things with page text objects, like split them into weird pieces or placed them in weird places. This will often, although not exclusively, happen at font style change boundaries (e.g. what happens if a piece of text you're trying to redact is partly bold and partly italic? - those two chunks will be in two separate text objects).

You may want to experiment with the `PdfParagraph` object, an in-development feature designed expressly to handle situations like this by dealing with text at a higher level than the page object level. But it's not yet finished, and won't be until after the release of crate version 1.0.

Notes on `PdfParagraph:` https://github.com/ajrcarey/pdfium-render/issues/29

**Comment by jymchng** [comment]
> _In theory_, it's straight-forward:
> 
> * For each page `p`
> * For each page object `o` on page `p`
> * If `o` is a page text object...
> * ... then retrieve the text inside `o`, search it for the target string, and replace it with the redacted string
> 
> You can see an example of iterating over every object in every page of a document at https://github.com/ajrcarey/pdfium-render/blob/master/examples/objects.rs.
> 
> _In practice_, you're likely to encounter situations where the application used to create the source PDF has done weird things with page text objects, like split them into weird pieces or placed them in weird places. This will often, although not exclusively, happen at font style change boundaries (e.g. what happens if a piece of text you're trying to redact is partly bold and partly italic? - those two chunks will be in two separate text objects, so the naive approach won't find them since neither text object contains the complete search target).
> 
> You may want to experiment with the `PdfParagraph` object, an in-development feature designed expressly to handle situations like this by dealing with text at a higher level than the page object level. But it's not yet finished, and won't be until after the release of crate version 1.0.
> 
> Notes on `PdfParagraph:` #29

@ajrcarey Thank you for your prompt reply.

Anyway, as I am not entirely familiar with C++ build tools/toolchain, do you mind sharing some resources on how I can statically linked to `Pdfium` at compile time?

Thank you.

**Comment by jymchng** [comment]
> _In theory_, it's straight-forward:
> 
> * For each page `p`
> * For each page object `o` on page `p`
> * If `o` is a page text object...
> * ... then retrieve the text inside `o`, search it for the target string, and replace it with the redacted string
> 
> You can see an example of iterating over every object in every page of a document at https://github.com/ajrcarey/pdfium-render/blob/master/examples/objects.rs.
> 
> _In practice_, you're likely to encounter situations where the application used to create the source PDF has done weird things with page text objects, like split them into weird pieces or placed them in weird places. This will often, although not exclusively, happen at font style change boundaries (e.g. what happens if a piece of text you're trying to redact is partly bold and partly italic? - those two chunks will be in two separate text objects, so the naive approach won't find them since neither text object contains the complete search target).
> 
> You may want to experiment with the `PdfParagraph` object, an in-development feature designed expressly to handle situations like this by dealing with text at a higher level than the page object level. But it's not yet finished, and won't be until after the release of crate version 1.0.
> 
> Notes on `PdfParagraph:` #29

This [line](https://github.com/ajrcarey/pdfium-render/blob/master/examples/objects.rs#L17) does not work since the type `.objects()` returns does not implement the `Iterator` trait.

**Comment by ajrcarey** [comment]
> This [line](https://github.com/ajrcarey/pdfium-render/blob/master/examples/objects.rs#L17) does not work since the type .objects() returns does not implement the Iterator trait.

It works fine for me using cargo run --example objects.

> Anyway, as I am not entirely familiar with C++ build tools/toolchain, do you mind sharing some resources on how I can statically linked to Pdfium at compile time?

Static linking is discussed at https://github.com/ajrcarey/pdfium-render?tab=readme-ov-file#static-linking. A sample build script is at https://github.com/ajrcarey/pdfium-render/issues/53. No C++ experience is necessary to build Pdfium from source - you will not be editing any C++ files - but if you are not comfortable building a static binary, then I suggest you use dynamic linking instead.
