### ISSUE TITLE
How to attach an external signature to a pdf

### ISSUE THREAD

**Issue by dev-with-no-username** [ajrcarey/pdfium-render#165]
Hi, first of all thanks for this great library!

Is there a way to attach an external signature (for example a pades) to a pdf using your library? I saw only how to get signature.

**Comment by ajrcarey** [comment]
Hi @dev-with-no-username , thank you for your question. You can review the signature functionality offered by Pdfium here:

https://pdfium.googlesource.com/pdfium/+/refs/heads/main/public/fpdf_signature.h

As you can see, there is no facility at present to add signatures to documents, only to inspect signatures that are already there. There is no intention prior to release 1.0 for `pdfium-render` to support any functionality that Pdfium does not directly provide itself. There may be scope for adding additional custom functionality after the release of 1.0, but that is some time away. So for now, unfortunately, the answer is no.
