### ISSUE TITLE
how to create a link annotation that link to local?

### ISSUE THREAD

**Issue by Xiaobaishushu25** [ajrcarey/pdfium-render#179]
I have read the example of creating annotations, but the link is to a specified address. I would like to know how to create a link and redirect to a specified page in the PDF. I searched the document and found GoToDestinationInSameDocument, but I don't know how to use it. For example, I want to set an invisible rectangular box on the first page, and click any area inside this box to jump to the second page. How can I achieve it? thank you.

**Comment by ajrcarey** [comment]
Hi @Xiaobaishushu25 , `pdfium-render` only exposes functionality that is directly provided by Pdfium itself. Pdfium provides the ability to create a URI link, but (as far as I am aware) no other types of links. As a result, only the creation of URI links is possible in `pdfium-render`.

Once the feature is available in Pdfium, I will be happy to add it here as well.

**Comment by ajrcarey** [comment]
Hi @Xiaobaishushu25 , `pdfium-render` only exposes functionality that is directly provided by Pdfium itself. Pdfium provides the ability to create a URI link, but (as far as I am aware) no other types of links. As a result, only the creation of URI links is possible in `pdfium-render`.

Once the feature is available in Pdfium, I will be happy to add it here as well.
