### ISSUE TITLE
Linking to system-provided libpdfium.so is prohibited in newer Android releases.

### ISSUE THREAD

**Issue by nagato-chan** [ajrcarey/pdfium-render#26]
Since the change from Android N apps could not access library under /system/lib[64], which marked as private.
https://github.com/android/ndk/issues/168

**Comment by ajrcarey** [comment]
I understand. Bundle a suitable `libpdfium.so` alongside your application as part of your APK and bind to it dynamically at runtime using `Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))` or similar, as per the documentation.

If you are using Gradle, you can place `libpdfium.so` builds for the three architectures supported by fat APKS - arm64, armv7, and i686 - into your application's `jniLibs/arm64-v8a`, `jniLibs/armeabi-v7a`, and `jniLibs/x86` folders. The exact placement in your filesystem will depend on the tools you are using to package your APK. For my own Android applications, having `libpdfium.so` in the same folder as my compiled Rust code is sufficient for `Pdfium::bind_to_library()` to find it at runtime.

**Comment by ajrcarey** [comment]
As this is a packaging issue rather than a bug in `pdfium-render`, I am closing the issue. Feel free to re-open if you have further questions, or if you believe `pdfium-render` contains a bug.

**Comment by nagato-chan** [comment]
Thanks! 

I was opened the issue just to let you know. Obviouly it is not the issue in `pdfium-render`. (I recommend you could update the doc of the section)

**Comment by ajrcarey** [comment]
Good idea, I'll add a note to the README.
