### ISSUE TITLE
Run in web worker

### ISSUE THREAD

**Issue by NyxCode** [ajrcarey/pdfium-render#37]
To run pdfium-render on the web, it's important to do the actual rendering in a [worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker). Otherwise, expensive operations block the UI. [However, `window` is not accessible within workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web_workers_api:~:text=workers%20run%20in%20another%20global%20context%20that%20is%20different%20from%20the%20current%20window.%20Thus%2C%20using%20the%20window%20shortcut%20to%20get%20the%20current%20global%20scope%20(instead%20of%20self)%20within%20a%20Worker%20will%20return%20an%20error.).  
Currently, running pdfium-render in a worker fails with
```
Uncaught (in promise) ReferenceError: Window is not defined
    at imports.wbg.__wbg_instanceof_Window_42f092928baaee84
```

**Comment by NyxCode** [comment]
```rust
        let table: WebAssembly::Table =
            Reflect::get(&window().unwrap(), &JsValue::from("wasmTable"))
                .map_err(|_| "Window.wasmTable not defined")?
                .into();
```
I'll do some experimentation to see if it's possible to get the `wasmTable` without relying on `window`.

**Comment by NyxCode** [comment]
Tested this [here](https://svelte-pdf-viewer.nyxcode.com/), and it works 🥳 (on chrome)

**Comment by ajrcarey** [comment]
Thank you for the PR, that's all excellent, I will update the README and release as 0.7.14 over the weekend.

**Comment by ajrcarey** [comment]
Fixed a bug in the WASM implementation of `FPDF_StructElement_GetStringAttribute()`. Updated README.
