### ISSUE TITLE
Add support for extracting URIs from page link actions.

### ISSUE THREAD

**Issue by reyjexter** [ajrcarey/pdfium-render#68]
What's the correct way to extract links from page? There appears to be implementation of handling FPDFLink on bindings.rs already but it's not being used anywhere.

Thanks

**Comment by ajrcarey** [comment]
Hi @reyjexter, thank you for raising the issue.

Pdfium defines two types of links, so let's just make sure we're talking about the same type :)

1. `FPDF_LINK`, a link normally attached to an annotation, although these can be placed freely on a page as well
2. `FPDF_WEBLINK`, clickable links automatically created by Pdfium as a courtesy when it recognises a text string that looks like a URL

I assume we're talking about the first type of link, not the second. You're right that the bindings to the FPDF_* functions related to links have already been added to `bindings.rs`. They're not hooked up to the high level interface yet, however.

Looking at the functions provided by Pdfium, it seems to me that `FPDFLink_Enumerate()` lets us iterate over all the links attached to a page. It should be relatively easy to create a collection in the `PdfPages` struct that provides access to this. I'm away from home at the moment, but I will look into adding this for you early next week when I return.

**Comment by ajrcarey** [comment]
PS I'm not sure I have a good sample document that has a bunch of links in it, so if you have some sample PDF files you can share, please do attach them to this issue.

**Comment by reyjexter** [comment]
Thanks for the explanation on difference between the two and I think that is indeed the first one. 

I'm not particulary familiar with Pdfium yet but here's an example PDF:

[https://file.io/9bACThvLs83P](https://file.io/9bACThvLs83P)

**Comment by reyjexter** [comment]
I made some changes on forked repo and on this commit which didn't have to use `FPDFLink_Enumerate` and does work for what we need but I don't know if this is correct or not:

https://github.com/ajrcarey/pdfium-render/compare/master...reyjexter:pdfium-render:master

This only added extra function on an existing `PdfPageLinkAnnotation` module.

**Comment by ajrcarey** [comment]
Yes, I think that's good. Just be aware that the URI text is actually 7-bit ASCII rather than UTF-16LE; no doubt your code works, but with a variety of string types supported by Pdfium, it may be worth updating your comments so as not to create confusion in future.

Because the FPDF_LINK and FPDF_ACTION types can be used in a variety of different places, I have taken a slightly different approach and broken these out into separate structs in the `pdfium-render` interface. Additionally, I have fleshed out the object hierarchy to support all action types, and added the ability to iterate over all links in the page using the new `PdfPage::links()` collection. It is not quite as succint as your approach, but allows for supporting all link and action types in the future, not just URI actions. An example using the functionality is in `examples/links.rs`.

**Comment by reyjexter** [comment]
Thanks for the this and as well as feedback and pointers. We will definitely be using the library that is released on from this main repository.

Does the `example/links.rs` suppose to work on Web Assembly? I tried updating our codes with version that is on master repo and it's not returning the links on example PDF. The difference from what we are doing though is we are passing a `Blob` instead of url though annotations/text are correctly being read. Here's the demo application I created:

https://github.com/reyjexter/pdfium-render-wasm/blob/master/src/lib.rs

Also, with this new functions, how are you able to find link(s) associated with an annotation? What are trying to create is a struct of text and annotation and return those information on browser together.

Thanks again!

**Comment by ajrcarey** [comment]
Yes, all functionality _should_ work on WASM except where explicitly marked. Let me see if I can reproduce the problem.

To retrieve the link associated with a link annotation, you first get the annotation from `PdfPages::annotations()`, unwrap it as a link annotation using `PdfPageAnnotation::as_link_annotation()`, and from there you should be able to retrieve the link itself using `PdfPageLinkAnnotation::link()`.

So, for example, something like:

````rust
for annotation in page.annotations().iter() {
    if Some(annotation) = annotation.as_link_annotation() {
        if Some(link) = annotation.link() {
            // ... do something with the link ...
        }
    }
}
````

**Comment by reyjexter** [comment]
The codes to extract link from an annotation works well. Thank!

**Comment by ajrcarey** [comment]
I can reproduce your WASM problem. This was due to a small bug in memory allocation in the WASM implementation of `FPDFLink_Enumerate()`. I have fixed this and updated the WASM example code at `examples/wasm.rs` so it outputs the links in the test document to the console.

**Comment by ajrcarey** [comment]
Made small adjustments to documentation. Bumped crate version in `Cargo.toml` to 0.7.31.

**Comment by reyjexter** [comment]
Thanks and I can also confirm this works correctly now.

**Comment by ajrcarey** [comment]
Excellent. Publishing to crates.io as release 0.7.31.
