### ISSUE TITLE
usize subtract in page_text.rs can underflow on certain PDFs

### ISSUE THREAD

**Issue by luketpeterson** [ajrcarey/pdfium-render#70]
In the function `chars_inside_rect()` in `page_text.rs`, sometimes the start and stop chars resolved by calling `get_char_near_point` return results where the start text offset falls after the end text offset.

Then an overflow occurs when start is subtracted from end to get the text span.

On PDFs generated by my credit card company (CapitalOne Financial), this problem is common.  I'm hesitant to upload the test PDF to GitHub, as it contains personal info.  I can share it with an individual person, however.

I will file a PR.

**Comment by ajrcarey** [comment]
Hi @luketpeterson, thank you for the PR - I really appreciate it. The change will be released as part of 0.7.32. No need to send a sensitive PDF.

**Comment by ajrcarey** [comment]
Bumped crate version in `Cargo.toml`. Updated `README.md`. Published to crates.io as version 0.7.32.
