### ISSUE TITLE
logic in chars example misses single character words at the end of an object

### ISSUE THREAD

**Issue by luketpeterson** [ajrcarey/pdfium-render#72]
The structure of the if-else clauses in the chars.rs example file means that a single character word that also comes at the end of an object won't be processed (printed).

This is because, In the current file, line 61 reads:
```rust
            } else if start_of_word.is_none() {
```
and this branch is taken for the first (non-space) character in a word.  But then the `else` clause line 66 won't be taken, meaning there will be no opportunity to process (print) the last word before the loop terminates.

I have a PR to address this by slightly rearranging the logic in the file.

Thank you.

**Comment by ajrcarey** [comment]
Hi @luketpeterson, excellent catch - I missed that edge case when I put together the example as part of #27, thank you for fixing my mistake :) Merged in time for 0.7.32.
