### ISSUE TITLE
Add support for getting page index from a bookmark destination

### ISSUE THREAD

**Issue by Nystik-gh** [ajrcarey/pdfium-render#86]
Would be great if `FPDFDest_GetDestPageIndex` was implemented on PdfBookmark or PdfDestination.

I'm currently in a situation where I need to do a reverse lookup on the bookmark titles in a PDF knowing only the page number.

**Comment by ajrcarey** [comment]
Hi @Nystik-gh , great idea! I will look at this for you in the week starting Mon 29 May.

**Comment by ajrcarey** [comment]
Added `PdfDestination::page_index()` function to retrieve page index via `FPDFDest_GetDestPageIndex()`.

If you have a sample document containing suitable links and are able to share it, that would be useful.

**Comment by ajrcarey** [comment]
As there have been no further comments, and I believe the original request is now resolved, I am closing the issue. Feel free to reopen if you feel the original request has not been resolved.
