### ISSUE TITLE
Lack of Printing Support

### ISSUE THREAD

**Issue by Kapocsi** [ajrcarey/pdfium-render#92]
Reading through the readme I noticed the explicit lack of support for printing "with the exception of certain functions specific to interactive scripting, user interaction, and **printing**" I am just wondering about the reason behind this; Is this something that is opposed by time limitation or by something else? Would an effort to add it into the repo be considered?

**Comment by ajrcarey** [comment]
Hi @Kapocsi , it's because it's entirely platform dependent (unless you are aware of a crate that can handle seamless cross-platform printing?). This makes it well outside the scope of this project.

If you already have the PDF file, why not just print it directly?

**Comment by Kapocsi** [comment]
I have been banging my head against a wall trying to solve this problem for a while, I know the Pdfium from google does support printing and was not sure why feature parity. If I do figure it out I was wondering if that would binding that this crate would be open too. 

As for if there is a existing solution; no. There is one small crate that uses CLI's from Windows but not much past that for windows (not sure about unix systems and CUPS). 

It is a very niche thing to want to wan't to print PDF's from code and has appropriately that much support in almost all languages (except Java funnily enough).

**Comment by ajrcarey** [comment]
(PS for macOS and Linux, you may be able to integrate with CUPS, which I believe is the default print system on both platforms: https://crates.io/crates/cups-sys)
