### ISSUE TITLE
pdfium_render::bitmap::PdfBitmapFormat::BRGx should be BGRx

### ISSUE THREAD

**Issue by frogtd** [ajrcarey/pdfium-render#96]
The headers have `FPDFBitmap_Gray`, `FPDFBitmap_BGR`, `FPDFBitmap_BGRx`, and `FPDFBitmap_BGRA`, but in the `PdfBitmapFormat` you appear to have made a typo and said `BRGx` instead of `BGRx`.

**Comment by ajrcarey** [comment]
Good spotting, thank you! The misspelled variant has been deprecated and a variant with the correct spelling introduced. Deprecated items will be removed in release 0.9.0. This fix will be included in release 0.8.7.
