### ISSUE TITLE
Add support for obtaining bezier curve control points

### ISSUE THREAD

**Issue by cemerick** [ajrcarey/pdfium-render#99]
Quoting from https://github.com/ajrcarey/pdfium-render/issues/55#issuecomment-1287890261:

>  Pdfium only allows you to retrieve the final destination point of each segment, not any other information about the segment. For instance, for a bezier curve segment, Pdfium does not provide any way to retrieve the control points of the curve.

Assuming this remains the case, some upstream work will be necessary. In either case, this is a clear gap that seems worth tracking explicitly, thus the issue.

**Comment by ajrcarey** [comment]
Hi @cemerick , you need to chase this upstream with the Pdfium project - once the functionality is added to Pdfium, then by all means open a new issue in this repo to have support added to `pdfium-render`. But `pdfium-render`'s repo is not the appropriate place to track bugs or missing functionality in other projects.

**Comment by cemerick** [comment]
Sure, sorry for the noise. :bow:
